### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by AzerSD** [clarabez/appium-en#1]
I'm not sure but I guess there's a typo in the documentation in here: 
https://github.com/clarabez/appium-en#environment-variables---windows
in installing Android SDK in the windows environment at step 3
isn't it  %ANDROID_HOME%\tools" instead of %ANDROID_HOME\tools%" ??

![Capture](https://user-images.githubusercontent.com/56733438/117596793-6ed0c400-b144-11eb-8e03-54e6773b961d.PNG)

**Comment by clarabez** [comment]
Yes, @AzerSD! You are right. I will adjust it right away. Thanks for reporting this.

**Comment by clarabez** [comment]
Adjusted! :)
